### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [rburkholder/nut2mqtt#1]
Following the instructions works perfectly until I run the "make" command and get: 

> $ make
[ 25%] Building CXX object src/CMakeFiles/nut2mqtt.dir/Config.cpp.o
In file included from /home/pi/nut2mqtt/src/Config.cpp:31:
/home/pi/nut2mqtt/src/Config.hpp:27:10: fatal error: ou/mqtt/config.hpp: No such file or directory
   27 | #include <ou/mqtt/config.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/nut2mqtt.dir/build.make:82: src/CMakeFiles/nut2mqtt.dir/Config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: src/CMakeFiles/nut2mqtt.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

Any ideas?

**Comment by rburkholder** [comment]
My notes need revamping, but bottom line, you'll need to clone, build and install https://github.com/rburkholder/repertory first to obtain the MQTT interface.  I factored it out as I found I use it 
across a number of my projects.

**Comment by bigfeetneedbigboots** [comment]
No luck. I ran:

> git clone https://github.com/rburkholder/repertory.git
cd repertory/
mkdir build
cd build/
cmake ..
make

Then at the 60% finished point I get:

> [ 60%] Building CXX object Telegram/CMakeFiles/telegram_static.dir/Bot.cpp.o
/home/pi/repertory/Telegram/Bot.cpp:30:10: fatal error: boost/json.hpp: No such file or directory
   30 | #include <boost/json.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Telegram/CMakeFiles/telegram_static.dir/build.make:95: Telegram/CMakeFiles/telegram_static.dir/Bot.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:192: Telegram/CMakeFiles/telegram_static.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

I don't want telegram but is there some sort of dependency on it? Would you please let me know the commands to run to get past this sticking point?

**Comment by rburkholder** [comment]
As shown in the repositories build instructions, you'll need:

```
sudo apt install libpaho-mqtt-dev

mkdir build
cd build

cmake \
-D CMAKE_BUILD_TYPE=Release \
-D OU_USE_STATIC_LIB=ON \
-D OU_USE_SHARED_LIB=OFF \
-D OU_USE_MQTT=ON \
-D OU_USE_Telegram=OFF \
..
sudo cmake --build . --target=install
```

**Comment by bigfeetneedbigboots** [comment]
Getting stuck on the sudo cmake command:

> $ sudo cmake --build . --target=install
Unknown argument --target=install
Usage: cmake --build <dir> [options] [-- [native-options]]
> Options:
>
>  <dir>          = Project binary directory to be built.
>  --parallel [<jobs>], -j [<jobs>]
>                 = Build in parallel using the given number of jobs. 
>                   If <jobs> is omitted the native build tool's 
>                   default number is used.
>                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
>                   specifies a default parallel level when this option
>                   is not given.
>  --target <tgt>..., -t <tgt>... 
>                 = Build <tgt> instead of default targets.
>  --config <cfg> = For multi-configuration tools, choose <cfg>.
>  --clean-first  = Build target 'clean' first, then build.
>                   (To clean only, use --target 'clean'.)
>  --verbose, -v  = Enable verbose output - if supported - including
>                   the build commands to be executed. 
>  --             = Pass remaining options to the native tool.

**Comment by rburkholder** [comment]
please show complete build, like this:

```
~/data/projects/repertory$ mkdir build
~/data/projects/repertory$ cd build
~/data/projects/repertory/build$ cmake \
-D CMAKE_BUILD_TYPE=Release \
-D OU_USE_STATIC_LIB=ON \
-D OU_USE_SHARED_LIB=OFF \
-D OU_USE_MQTT=ON \
-D OU_USE_Telegram=OFF \
..
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type set to Release
-- Repertory will be installed to /usr/local
-- Installing LIB components to /usr/local/lib
-- Installing BIN components to /usr/local/bin
-- Installing INCLUDE components to /usr/local/include
-- Installing CMAKE components to /usr/local/
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rpb/data/projects/repertory/build
~/data/projects/repertory/build$ sudo cmake --build . --target=install
[sudo] password for rpb:
[ 50%] Building CXX object MQTT/CMakeFiles/mqtt_static.dir/mqtt.cpp.o
[100%] Linking CXX static library libou_mqtt.a
[100%] Built target mqtt_static
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libou_mqtt.a
-- Installing: /usr/local/include/ou/mqtt/config.hpp
-- Installing: /usr/local/include/ou/mqtt/mqtt.hpp
~/data/projects/repertory/build$ cmake --version
cmake version 3.25.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by bigfeetneedbigboots** [comment]
Same as previous comment. I get similar until the sudo cmake command which has an unknown argument of "--target=install".

I'm doing this on a Raspberry Pi 4 running the OctoPi version of Raspbian. Does that shed any light on the issue?

**Comment by rburkholder** [comment]
what is 'cmake --version'?

I'm not familiar with what 'Raspberry Pi 4 running the OctoPi version of Raspbian' functions are provided.

**Comment by bigfeetneedbigboots** [comment]
> $ cmake --version
cmake version 3.18.4
>
> CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by rburkholder** [comment]
ok, you might be able to leave the --target=install off, then do a manual 'sudo make install'
